# site settings
title: Welcome to Pure SPA
subtitle: RELAX YOUR BODY IN A WHILE
email: pure.relaxs.spas@gmail.com
description: 
baseurl:  # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author:
street_address:
city: Tainan
state: TW
zip_code: 
country: Tainan of Taiwan
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
